spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/email_checker_bot_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

email:
  providers:
    yandex:
      host: imap.yandex.com
      port: 993
      ssl: true
      auth: XOAUTH2
      auth-url: https://oauth.yandex.ru
      client-id: e0261684b7fb476c8049cfe487c9c89b
      client-secret: 3ac020b46deb4828a855c7b46b8a57ad
      settings-url: https://mail.yandex.ru/#setup/client
    mailru:
      host: imap.mail.ru
      port: 993
      ssl: true
      auth: XOAUTH2
      auth-url: https://oauth.mail.ru
      client-id: c2e5ae1d247a4e1b827db598ff988021
      client-secret: a3d25162637f42028f7d83f1c10e1f2c
      settings-url: https://help.mail.ru/mail/security/apps/
  check:
    delay: PT1M

fixed:
  thread:
    pool:
      size: 10

rest:
  yandex:
    user-info-url: https://login.yandex.ru
    oauth-url: https://oauth.yandex.ru
    read-timeout: 120s
    connect-timeout: 120s
  mailru:
    url: https://oauth.mail.ru
    read-timeout: 120s
    connect-timeout: 120s

messages:
  url: http://127.0.0.1:8080/api/v1/messages

redirect:
  uri: http://127.0.0.1:8080/api/v1/oauth/receiver

telegram:
  bot:
    token: 8011278387:AAHWhDVCfXxFtWIdx3SK_rUKIkQer4zmKmI
    username: Slava