-- liquibase formatted sql

-- changeset vyach:1730231122420-1
CREATE TABLE user_emails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email_provider VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    token VARCHAR(255) NOT NULL,
    last_message_uid BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_emails PRIMARY KEY (id)
);

-- changeset vyach:1730231122420-2
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telegram_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset vyach:1730231122420-3
ALTER TABLE user_emails
    ADD CONSTRAINT FK_USER_EMAILS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

